export const GET_LATEST_BLOCKS = 'GET_LATEST_BLOCKS';
export const GET_LATEST_BLOCKS_SUCCESS = 'GET_LATEST_BLOCKS_SUCCESS';
export const GET_LATEST_BLOCKS_FAILURE = 'GET_LATEST_BLOCKS_FAILURE';
export const GET_SELECTED_BLOCK_DETAILS = 'GET_SELECTED_BLOCK_DETAILS';
export const GET_SELECTED_BLOCK_DETAILS_SUCCESS =
	'GET_SELECTED_BLOCK_DETAILS_SUCCESS';
export const GET_SELECTED_BLOCK_DETAILS_FAILURE =
	'GET_SELECTED_BLOCK_DETAILS_FAILURE';
